# Generated by Django 2.2.5 on 2019-10-15 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('raio_distancia', models.IntegerField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
    ]
