version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
     - ./.env
    ports: 
      - 5050:80
  db:
    image: postgres
    restart: always
    env_file: 
     - ./.env
    ports: 
     - 5432:5432
    depends_on: 
     - pgadmin 